name: notifications_listener_service
description: Notifications listener service an android plugin to listen for all upcoming notifications
version: 0.0.2
homepage: https://github.com/adhamkhaledabdelwahab/notification_listener_service

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: kh.ad.notifications_listener_service
        pluginClass: NotificationsListenerServicePlugin
